apiVersion: batch/v1
kind: Job
metadata:
  name: kbuild-demo
spec:
  template:
    spec:
      containers:
      - name: init-static
        image: gcr.io/priya-wadhwa/executor:latest
        command: ["/work-dir/executor",  "--context=kbuild-demo", "--name=gcr.io/priya-wadhwa/kbuild:example", "--dockerfile=/workspace/Dockerfile"]
        volumeMounts:
          - name: dockerfile-volume
            mountPath: /workspace/
      restartPolicy: Never
      volumes:
        - name: dockerfile-volume
          configMap:
            name: dockerfile-config
            items:
              - key: Dockerfile
                path: Dockerfile
